Mod4 branch
Valevach90/JavaUpSkill pull request #5
Opened 2021-03-27 12:34 UTC by Valevach90

2021-03-29 11:23 UTC, plisunov requested changes

2021-03-29 11:23 UTC, plisunov commented on mod2/src/main/java/org/example/ParserJson.java
> +            LOGGER.info("configuration data is read" );
Data is not readed in this line

2021-03-29 11:23 UTC, plisunov commented on mod2/src/main/java/org/example/RenameFiles.java
> +                LOGGER.info("files are renamed");
"File is exist. Rename started" message will be better.

2021-03-29 11:23 UTC, plisunov commented on mod2/src/main/java/org/example/RenameFiles.java
> +                LOGGER.info("files "+files.getFileName()+ " are not renamed");
This message is not correct.

2021-03-29 11:23 UTC, plisunov commented on mod2/src/main/resources/log4j.properties
> +log4j.appender.file.File=C:\\Users\\Dmitry\\IdeaProjects\\JavaUpSkill\\mod2\\src\\log\\log_file.log
Can we use relative path for file? Also log file should not be placed to code path

2021-04-07 18:16 UTC, Valevach90 reviewed
последний вариант программы

2021-04-22 19:46 UTC, merged